using System;
using Google.Protobuf.Reflection;

namespace Hydra.Api.User;

public static class EnumsReflection
{
	private static FileDescriptor descriptor;

	public static FileDescriptor Descriptor => descriptor;

	static EnumsReflection()
	{
		byte[] descriptorData = Convert.FromBase64String("ChBVc2VyL0VudW1zLnByb3RvEg5IeWRyYS5BcGkuVXNlciqWAQoQVXNlclN0" + "YXRlT3duVHlwZRIfChtVU0VSX1NUQVRFX09XTl9UWVBFX1VOS05PV04QABIh" + "Ch1VU0VSX1NUQVRFX09XTl9UWVBFX0RPTlRfSEFWRRABEh4KGlVTRVJfU1RB" + "VEVfT1dOX1RZUEVfQk9VR0hUEAISHgoaVVNFUl9TVEFURV9PV05fVFlQRV9S" + "RU5URUQQAyrHAQoRVXNlclN0YXRlRGF0YVR5cGUSIAocVVNFUl9TVEFURV9E" + "QVRBX1RZUEVfVU5LTk9XThAAEiIKHlVTRVJfU1RBVEVfREFUQV9UWVBFX05V" + "TUVSSUNBTBABEiMKH1VTRVJfU1RBVEVfREFUQV9UWVBFX1RJTUVfQkFTRUQQ" + "AhIfChtVU0VSX1NUQVRFX0RBVEFfVFlQRV9TVFJJTkcQAxImCiJVU0VSX1NU" + "QVRFX0RBVEFfVFlQRV9WRUNUT1JfU1RSSU5HEAQqhQIKD1VzZXJTdGF0ZU9w" + "VHlwZRIeChpVU0VSX1NUQVRFX09QX1RZUEVfVU5LTk9XThAAEhoKFlVTRVJf" + "U1RBVEVfT1BfVFlQRV9BREQQARIdChlVU0VSX1NUQVRFX09QX1RZUEVfUkVN" + "T1ZFEAISGwoXVVNFUl9TVEFURV9PUF9UWVBFX1JFTlQQAxIaChZVU0VSX1NU" + "QVRFX09QX1RZUEVfU0VUEAQSGgoWVVNFUl9TVEFURV9PUF9UWVBFX1NVQhAF" + "Eh4KGlVTRVJfU1RBVEVfT1BfVFlQRV9SRVFVSVJFEAYSIgoeVVNFUl9TVEFU" + "RV9PUF9UWVBFX1JFUVVJUkVMRVNTEAdiBnByb3RvMw==");
		descriptor = FileDescriptor.FromGeneratedCode(descriptorData, new FileDescriptor[0], new GeneratedClrTypeInfo(new Type[3]
		{
			typeof(UserStateOwnType),
			typeof(UserStateDataType),
			typeof(UserStateOpType)
		}, null, null));
	}
}
