namespace Manatee.Json.Schema;

public static class MetaSchemas
{
	public static readonly JsonSchema Draft04 = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft04
	}.IdDraft04("http://json-schema.org/draft-04/schema#").Schema("http://json-schema.org/draft-04/schema#").Description("Core schema meta-schema")
		.Definition("schemaArray", new JsonSchema().Type(JsonSchemaType.Array).MinItems(1u).Items(new JsonSchema().RefRoot()))
		.Definition("positiveInteger", new JsonSchema().Type(JsonSchemaType.Integer).Minimum(0.0))
		.Definition("positiveIntegerDefault0", new JsonSchema().AllOf(new JsonSchema().Ref("#/definitions/positiveInteger"), new JsonSchema().Default(0.0)))
		.Definition("simpleTypes", new JsonSchema().Enum("array", "boolean", "integer", "null", "number", "object", "string"))
		.Definition("stringArray", new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Type(JsonSchemaType.String)).MinItems(1u)
			.UniqueItems(unique: true))
		.Type(JsonSchemaType.Object)
		.Property("id", new JsonSchema().Type(JsonSchemaType.String))
		.Property("$schema", new JsonSchema().Type(JsonSchemaType.String))
		.Property("title", new JsonSchema().Type(JsonSchemaType.String))
		.Property("description", new JsonSchema().Type(JsonSchemaType.String))
		.Property("default", new JsonSchema())
		.Property("multipleOf", new JsonSchema().Type(JsonSchemaType.Number).Minimum(0.0).ExclusiveMinimumDraft04(isExclusive: true))
		.Property("maximum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMaximum", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("minimum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMinimum", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("maxLength", new JsonSchema().Ref("#/definitions/positiveInteger"))
		.Property("minLength", new JsonSchema().Ref("#/definitions/positiveIntegerDefault0"))
		.Property("pattern", new JsonSchema().Type(JsonSchemaType.String).Format(Format.Regex))
		.Property("additionalItems", new JsonSchema().AnyOf(new JsonSchema().Type(JsonSchemaType.Boolean), new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("items", new JsonSchema().AnyOf(new JsonSchema().RefRoot(), new JsonSchema().Ref("#/definitions/schemaArray")).Default(new JsonObject()))
		.Property("maxItems", new JsonSchema().Ref("#/definitions/positiveInteger"))
		.Property("minItems", new JsonSchema().Ref("#/definitions/positiveIntegerDefault0"))
		.Property("uniqueItems", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("maxProperties", new JsonSchema().Ref("#/definitions/positiveInteger"))
		.Property("minProperties", new JsonSchema().Ref("#/definitions/positiveIntegerDefault0"))
		.Property("required", new JsonSchema().Ref("#/definitions/stringArray"))
		.Property("additionalProperties", new JsonSchema().AnyOf(new JsonSchema().Type(JsonSchemaType.Boolean), new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("definitions", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("properties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("patternProperties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("dependencies", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().AnyOf(new JsonSchema().RefRoot(), new JsonSchema().Ref("#/definitions/stringArray"))))
		.Property("enum", new JsonSchema().Type(JsonSchemaType.Array).MinItems(1u).UniqueItems(unique: true))
		.Property("type", new JsonSchema().AnyOf(new JsonSchema().Ref("#/definitions/simpleTypes"), new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Ref("#/definitions/simpleTypes")).MinItems(1u)
			.UniqueItems(unique: true)))
		.Property("format", new JsonSchema().Type(JsonSchemaType.String))
		.Property("allOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("anyOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("oneOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("not", new JsonSchema().RefRoot())
		.Dependency("exclusiveMaximum", "maximum")
		.Dependency("exclusiveMinimum", "minimum")
		.Default(new JsonObject());

	public static readonly JsonSchema Draft06 = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft06
	}.Schema("http://json-schema.org/draft-06/schema#").Id("http://json-schema.org/draft-06/schema#").Title("Core schema meta-schema")
		.Definition("schemaArray", new JsonSchema().Type(JsonSchemaType.Array).MinItems(1u).Items(new JsonSchema().RefRoot()))
		.Definition("nonNegativeInteger", new JsonSchema().Type(JsonSchemaType.Integer).Minimum(0.0))
		.Definition("nonNegativeIntegerDefault0", new JsonSchema().AllOf(new JsonSchema().Ref("#/definitions/nonNegativeInteger"), new JsonSchema().Default(0.0)))
		.Definition("simpleTypes", new JsonSchema().Enum("array", "boolean", "integer", "null", "number", "object", "string"))
		.Definition("stringArray", new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Type(JsonSchemaType.String)).UniqueItems(unique: true)
			.Default(new JsonArray()))
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("$id", new JsonSchema().Type(JsonSchemaType.String).Format(Format.UriReference))
		.Property("$schema", new JsonSchema().Type(JsonSchemaType.String).Format(Format.Uri))
		.Property("$ref", new JsonSchema().Type(JsonSchemaType.String).Format(Format.UriReference))
		.Property("title", new JsonSchema().Type(JsonSchemaType.String))
		.Property("description", new JsonSchema().Type(JsonSchemaType.String))
		.Property("default", new JsonSchema())
		.Property("examples", new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema()))
		.Property("multipleOf", new JsonSchema().Type(JsonSchemaType.Number).ExclusiveMinimum(0.0))
		.Property("maximum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMaximum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("minimum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMinimum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("maxLength", new JsonSchema().Ref("#/definitions/nonNegativeInteger"))
		.Property("minLength", new JsonSchema().Ref("#/definitions/nonNegativeIntegerDefault0"))
		.Property("pattern", new JsonSchema().Type(JsonSchemaType.String).Format(Format.Regex))
		.Property("additionalItems", new JsonSchema().RefRoot())
		.Property("items", new JsonSchema().AnyOf(new JsonSchema().RefRoot(), new JsonSchema().Ref("#/definitions/schemaArray")).Default(new JsonObject()))
		.Property("maxItems", new JsonSchema().Ref("#/definitions/nonNegativeInteger"))
		.Property("minItems", new JsonSchema().Ref("#/definitions/nonNegativeIntegerDefault0"))
		.Property("uniqueItems", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("contains", new JsonSchema().RefRoot())
		.Property("maxProperties", new JsonSchema().Ref("#/definitions/nonNegativeInteger"))
		.Property("minProperties", new JsonSchema().Ref("#/definitions/nonNegativeIntegerDefault0"))
		.Property("required", new JsonSchema().Ref("#/definitions/stringArray"))
		.Property("additionalProperties", new JsonSchema().RefRoot())
		.Property("definitions", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("properties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("patternProperties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("dependencies", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().AnyOf(new JsonSchema().RefRoot(), new JsonSchema().Ref("#/definitions/stringArray"))))
		.Property("propertyNames", new JsonSchema().RefRoot())
		.Property("const", new JsonSchema())
		.Property("enum", new JsonSchema().Type(JsonSchemaType.Array).MinItems(1u).UniqueItems(unique: true))
		.Property("type", new JsonSchema().AnyOf(new JsonSchema().Ref("#/definitions/simpleTypes"), new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Ref("#/definitions/simpleTypes")).MinItems(1u)
			.UniqueItems(unique: true)))
		.Property("format", new JsonSchema().Type(JsonSchemaType.String))
		.Property("allOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("anyOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("oneOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("not", new JsonSchema().RefRoot())
		.Default(new JsonObject());

	public static JsonSchema Draft07 = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft07
	}.Schema("http://json-schema.org/draft-07/schema#").Id("http://json-schema.org/draft-07/schema#").Title("Core schema meta-schema")
		.Definition("schemaArray", new JsonSchema().Type(JsonSchemaType.Array).MinItems(1u).Items(new JsonSchema().RefRoot()))
		.Definition("nonNegativeInteger", new JsonSchema().Type(JsonSchemaType.Integer).Minimum(0.0))
		.Definition("nonNegativeIntegerDefault0", new JsonSchema().AllOf(new JsonSchema().Ref("#/definitions/nonNegativeInteger"), new JsonSchema().Default(0.0)))
		.Definition("simpleTypes", new JsonSchema().Enum("array", "boolean", "integer", "null", "number", "object", "string"))
		.Definition("stringArray", new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Type(JsonSchemaType.String)).UniqueItems(unique: true)
			.Default(new JsonArray()))
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("$id", new JsonSchema().Type(JsonSchemaType.String).Format(Format.UriReference))
		.Property("$schema", new JsonSchema().Type(JsonSchemaType.String).Format(Format.Uri))
		.Property("$ref", new JsonSchema().Type(JsonSchemaType.String).Format(Format.UriReference))
		.Property("$comment", new JsonSchema().Type(JsonSchemaType.String))
		.Property("title", new JsonSchema().Type(JsonSchemaType.String))
		.Property("description", new JsonSchema().Type(JsonSchemaType.String))
		.Property("default", true)
		.Property("readOnly", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("writeOnly", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("examples", new JsonSchema().Type(JsonSchemaType.Array).Items(true))
		.Property("multipleOf", new JsonSchema().Type(JsonSchemaType.Number).ExclusiveMinimum(0.0))
		.Property("maximum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMaximum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("minimum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMinimum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("maxLength", new JsonSchema().Ref("#/definitions/nonNegativeInteger"))
		.Property("minLength", new JsonSchema().Ref("#/definitions/nonNegativeIntegerDefault0"))
		.Property("pattern", new JsonSchema().Type(JsonSchemaType.String).Format(Format.Regex))
		.Property("additionalItems", new JsonSchema().RefRoot())
		.Property("items", new JsonSchema().AnyOf(new JsonSchema().RefRoot(), new JsonSchema().Ref("#/definitions/schemaArray")).Default(true))
		.Property("maxItems", new JsonSchema().Ref("#/definitions/nonNegativeInteger"))
		.Property("minItems", new JsonSchema().Ref("#/definitions/nonNegativeIntegerDefault0"))
		.Property("uniqueItems", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("contains", new JsonSchema().RefRoot())
		.Property("maxProperties", new JsonSchema().Ref("#/definitions/nonNegativeInteger"))
		.Property("minProperties", new JsonSchema().Ref("#/definitions/nonNegativeIntegerDefault0"))
		.Property("required", new JsonSchema().Ref("#/definitions/stringArray"))
		.Property("additionalProperties", new JsonSchema().RefRoot())
		.Property("definitions", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("properties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).Default(new JsonObject()))
		.Property("patternProperties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RefRoot()).PropertyNames(new JsonSchema().Format(Format.Regex))
			.Default(new JsonObject()))
		.Property("dependencies", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().AnyOf(new JsonSchema().RefRoot(), new JsonSchema().Ref("#/definitions/stringArray"))))
		.Property("propertyNames", new JsonSchema().RefRoot())
		.Property("const", true)
		.Property("enum", new JsonSchema().Type(JsonSchemaType.Array).Items(true).MinItems(1u)
			.UniqueItems(unique: true))
		.Property("type", new JsonSchema().AnyOf(new JsonSchema().Ref("#/definitions/simpleTypes"), new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Ref("#/definitions/simpleTypes")).MinItems(1u)
			.UniqueItems(unique: true)))
		.Property("format", new JsonSchema().Type(JsonSchemaType.String))
		.Property("contentMediaType", new JsonSchema().Type(JsonSchemaType.String))
		.Property("contentEncoding", new JsonSchema().Type(JsonSchemaType.String))
		.Property("if", new JsonSchema().RefRoot())
		.Property("then", new JsonSchema().RefRoot())
		.Property("else", new JsonSchema().RefRoot())
		.Property("allOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("anyOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("oneOf", new JsonSchema().Ref("#/definitions/schemaArray"))
		.Property("not", new JsonSchema().RefRoot())
		.Default(true);

	public static readonly JsonSchema Draft2019_09 = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft2019_09
	}.Schema("https://json-schema.org/draft/2019-09/schema").Id("https://json-schema.org/draft/2019-09/schema").Vocabulary(SchemaVocabularies.Core, required: true)
		.Vocabulary(SchemaVocabularies.Applicator, required: true)
		.Vocabulary(SchemaVocabularies.Validation, required: true)
		.Vocabulary(SchemaVocabularies.MetaData, required: true)
		.Vocabulary(SchemaVocabularies.Format, required: false)
		.Vocabulary(SchemaVocabularies.Content, required: true)
		.RecursiveAnchor(value: true)
		.Title("Core and Validation specifications meta-schema")
		.AllOf(new JsonSchema().Ref("meta/core"), new JsonSchema().Ref("meta/applicator"), new JsonSchema().Ref("meta/validation"), new JsonSchema().Ref("meta/meta-data"), new JsonSchema().Ref("meta/format"), new JsonSchema().Ref("meta/content"))
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("definitions", new JsonSchema().Comment("While no longer an official keyword as it is replaced by $defs, this keyword is retained in the meta-schema to prevent incompatible extensions as it remains in common use.").Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RecursiveRefRoot())
			.Default(new JsonObject()))
		.Property("dependencies", new JsonSchema().Comment("\"dependencies\" is no longer a keyword, but schema authors should avoid redefining it to facilitate a smooth transition to \"dependentSchemas\" and \"dependentRequired\"").Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().AnyOf(new JsonSchema().RecursiveRefRoot(), new JsonSchema().Ref("meta/validation#/$defs/stringArray"))));

	public static readonly JsonSchema Draft2019_09_Core = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft2019_09
	}.Schema("https://json-schema.org/draft/2019-09/schema").Id("https://json-schema.org/draft/2019-09/meta/core").Vocabulary(SchemaVocabularies.Core, required: true)
		.RecursiveAnchor(value: true)
		.Title("Core vocabulary meta-schema")
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("$id", new JsonSchema().Type(JsonSchemaType.String).Format(Format.UriReference).Comment("Non-empty fragments not allowed.")
			.Pattern("^[^#]*#?$"))
		.Property("$schema", new JsonSchema().Type(JsonSchemaType.String).Format(Format.Uri))
		.Property("$anchor", new JsonSchema().Type(JsonSchemaType.String).Pattern("^[A-Za-z][-A-Za-z0-9.:_]*$"))
		.Property("$ref", new JsonSchema().Type(JsonSchemaType.String).Format(Format.UriReference))
		.Property("$recursiveRef", new JsonSchema().Type(JsonSchemaType.String).Format(Format.UriReference))
		.Property("$recursiveAnchor", new JsonSchema().Type(JsonSchemaType.Boolean).Const(true).Default(false))
		.Property("$vocabulary", new JsonSchema().Type(JsonSchemaType.Object).PropertyNames(new JsonSchema().Type(JsonSchemaType.String).Format(Format.Uri)).AdditionalProperties(new JsonSchema().Type(JsonSchemaType.Boolean)))
		.Property("$comment", new JsonSchema().Type(JsonSchemaType.String))
		.Property("$defs", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RecursiveRefRoot()).Default(new JsonObject()));

	public static readonly JsonSchema Draft2019_09_Applicator = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft2019_09
	}.Schema("https://json-schema.org/draft/2019-09/schema").Id("https://json-schema.org/draft/2019-09/meta/applicator").Vocabulary(SchemaVocabularies.Applicator, required: true)
		.RecursiveAnchor(value: true)
		.Title("Applicator vocabulary meta-schema")
		.Property("additionalItems", new JsonSchema().RecursiveRefRoot())
		.Property("unevaluatedItems", new JsonSchema().RecursiveRefRoot())
		.Property("items", new JsonSchema().AnyOf(new JsonSchema().RecursiveRefRoot(), new JsonSchema().Ref("#/$defs/schemaArray")))
		.Property("contains", new JsonSchema().RecursiveRefRoot())
		.Property("additionalProperties", new JsonSchema().RecursiveRefRoot())
		.Property("unevaluatedProperties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RecursiveRefRoot()))
		.Property("properties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RecursiveRefRoot()).Default(new JsonObject()))
		.Property("patternProperties", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RecursiveRefRoot()).PropertyNames(new JsonSchema().Format(Format.Regex))
			.Default(new JsonObject()))
		.Property("dependentSchemas", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().RecursiveRefRoot()))
		.Property("propertyNames", new JsonSchema().RecursiveRefRoot())
		.Property("if", new JsonSchema().RecursiveRefRoot())
		.Property("then", new JsonSchema().RecursiveRefRoot())
		.Property("else", new JsonSchema().RecursiveRefRoot())
		.Property("allOf", new JsonSchema().Ref("#/$defs/schemaArray"))
		.Property("anyOf", new JsonSchema().Ref("#/$defs/schemaArray"))
		.Property("oneOf", new JsonSchema().Ref("#/$defs/schemaArray"))
		.Property("not", new JsonSchema().RecursiveRefRoot())
		.Def("schemaArray", new JsonSchema().Type(JsonSchemaType.Array).MinItems(1u).Items(new JsonSchema().RecursiveRefRoot()));

	public static readonly JsonSchema Draft2019_09_MetaData = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft2019_09
	}.Schema("https://json-schema.org/draft/2019-09/schema").Id("https://json-schema.org/draft/2019-09/meta/meta-data").Vocabulary(SchemaVocabularies.MetaData, required: true)
		.RecursiveAnchor(value: true)
		.Title("Meta-data vocabulary meta-schema")
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("title", new JsonSchema().Type(JsonSchemaType.String))
		.Property("description", new JsonSchema().Type(JsonSchemaType.String))
		.Property("default", true)
		.Property("deprecated", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("readOnly", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("examples", new JsonSchema().Type(JsonSchemaType.Array).Items(true));

	public static readonly JsonSchema Draft2019_09_Validation = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft2019_09
	}.Schema("https://json-schema.org/draft/2019-09/schema").Id("https://json-schema.org/draft/2019-09/meta/validation").Vocabulary(SchemaVocabularies.Validation, required: true)
		.RecursiveAnchor(value: true)
		.Title("Validation vocabulary meta-schema")
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("multipleOf", new JsonSchema().Type(JsonSchemaType.Number).ExclusiveMinimum(0.0))
		.Property("maximum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMaximum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("minimum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("exclusiveMinimum", new JsonSchema().Type(JsonSchemaType.Number))
		.Property("maxLength", new JsonSchema().Ref("#/$defs/nonNegativeInteger"))
		.Property("minLength", new JsonSchema().Ref("#/$defs/nonNegativeIntegerDefault0"))
		.Property("pattern", new JsonSchema().Type(JsonSchemaType.String).Format(Format.Regex))
		.Property("maxItems", new JsonSchema().Ref("#/$defs/nonNegativeInteger"))
		.Property("minItems", new JsonSchema().Ref("#/$defs/nonNegativeIntegerDefault0"))
		.Property("uniqueItems", new JsonSchema().Type(JsonSchemaType.Boolean).Default(false))
		.Property("maxContains", new JsonSchema().Ref("#/$defs/nonNegativeInteger"))
		.Property("minContains", new JsonSchema().Ref("#/$defs/nonNegativeInteger").Default(1.0))
		.Property("maxProperties", new JsonSchema().Ref("#/$defs/nonNegativeInteger"))
		.Property("minProperties", new JsonSchema().Ref("#/$defs/nonNegativeIntegerDefault0"))
		.Property("required", new JsonSchema().Ref("#/$defs/stringArray"))
		.Property("dependentRequired", new JsonSchema().Type(JsonSchemaType.Object).AdditionalProperties(new JsonSchema().Ref("#/$defs/stringArray")))
		.Property("const", true)
		.Property("enum", new JsonSchema().Type(JsonSchemaType.Array).Items(true))
		.Property("type", new JsonSchema().AnyOf(new JsonSchema().Ref("#/$defs/simpleTypes"), new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Ref("#/$defs/simpleTypes")).MinItems(1u)
			.UniqueItems(unique: true)))
		.Def("nonNegativeInteger", new JsonSchema().Type(JsonSchemaType.Integer).Minimum(0.0))
		.Def("nonNegativeIntegerDefault0", new JsonSchema().Ref("#/$defs/nonNegativeInteger").Default(0.0))
		.Def("simpleTypes", new JsonSchema().Enum("array", "boolean", "integer", "null", "number", "object", "string"))
		.Def("stringArray", new JsonSchema().Type(JsonSchemaType.Array).Items(new JsonSchema().Type(JsonSchemaType.String)).UniqueItems(unique: true)
			.Default(new JsonArray()));

	public static readonly JsonSchema Draft2019_09_Format = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft2019_09
	}.Schema("https://json-schema.org/draft/2019-09/schema").Id("https://json-schema.org/draft/2019-09/meta/format").Vocabulary(SchemaVocabularies.Format, required: true)
		.RecursiveAnchor(value: true)
		.Title("Format vocabulary meta-schema")
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("format", new JsonSchema().Type(JsonSchemaType.String));

	public static readonly JsonSchema Draft2019_09_Content = new JsonSchema
	{
		SupportedVersions = JsonSchemaVersion.Draft2019_09
	}.Schema("https://json-schema.org/draft/2019-09/schema").Id("https://json-schema.org/draft/2019-09/meta/content").Vocabulary(SchemaVocabularies.Content, required: true)
		.RecursiveAnchor(value: true)
		.Title("Content vocabulary meta-schema")
		.Type(JsonSchemaType.Boolean | JsonSchemaType.Object)
		.Property("contentMediaType", new JsonSchema().Type(JsonSchemaType.String))
		.Property("contentEncoding", new JsonSchema().Type(JsonSchemaType.String))
		.Property("contentSchema", new JsonSchema().RecursiveRefRoot());
}
