using Google.Protobuf.Reflection;

namespace Hydra.Api.Zen.ZenTournaments;

public enum TournamentType
{
	[OriginalName("TOURNAMENT_TYPE_NONE")]
	None,
	[OriginalName("TOURNAMENT_TYPE_PREDEFINED")]
	Predefined,
	[OriginalName("TOURNAMENT_TYPE_AUTO_GENERATED")]
	AutoGenerated,
	[OriginalName("TOURNAMENT_TYPE_USER_GENERATED")]
	UserGenerated
}
